- name: This playbook demonstrates invoking our custom ansible module
  hosts: rocky 
  tasks:
  - name: Invoke custom ansible module
    hello: message="Advanced Ansible"
    register: output

  - debug: var=output
