- name: This playbook will install nginx web server, configures web root folder, deploy custom web page
  hosts: all
  tasks:
  - name: Install nginx web server in Ubuntu ansible node
    apt: name=nginx state=latest update_cache=yes
