version: 3

images:
  base_image:
    name: quay.io/rockylinux/rockylinux:9

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt


additional_build_steps:
  prepend_base:
    - RUN echo "🛠 Starting EE build (base phase)"
    - RUN dnf install -y curl git rsync --allowerasing
  append_final:
    - RUN echo "✅ EE build complete"

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--ignore-certs --no-cache --server https://galaxy.ansible.com"
